name: Deploy Infra (CDK)

on:
  push:
    branches: ["main"]
    paths:
      - "cdk_infra_test/**"
      - "app.py"
      - "requirements.txt"
      - "cdk.json"
  workflow_dispatch:
    inputs:
      action:
        description: CDK action
        required: true
        type: choice
        options:
          - synth
          - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Synth CDK
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'synth')
          || github.event_name == 'push'
        run: cdk synth

      - name: Deploy CDK
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy')
          || github.event_name == 'push'
        run: cdk deploy --require-approval never
